### ISSUE TITLE
Reexport raw() and other helpers

### ISSUE THREAD

**Issue by Turbo87** [kellyselden/ember-awesome-macros#264]
It seems annoying that you have to import `raw()` and `computed()` from a different addon than `ember-awesome-macros` itself. IMHO we should reexport those macros if we depend on them as our own public API.

**Comment by kellyselden** [comment]
I'm for this if anyone wants to tackle it before I get to it.

**Comment by Turbo87** [comment]
@kellyselden I assume you haven't had time yet?

**Comment by kellyselden** [comment]
@Turbo87 Not yet.

**Comment by mriska** [comment]
If I read the code correctly, `raw` is already re-exported but with a deprecation warning. For fixing `raw`, I guess it would just be a matter of removing the deprecation and changing the documentation? It looks like that would remove a lot of warnings from the tests as well that are caused by the deprecation.

I could give this a try.

**Comment by mriska** [comment]
And `computed` looks like it would be handled the exact same way.
