### ISSUE TITLE
Hash merge is missing

### ISSUE THREAD

**Issue by cbou** [kellyselden/ember-awesome-macros#281]
It would be great to be able to merge `hash` computed properties from parent or mixins.

If possible I guess the best would be to make it compatible with by `mergedProperties`.
https://emberjs.com/api/classes/Ember.Object.html#property_mergedProperties

Or something like
```
value1: hash({
  prop1: 'source1',
  prop2: hash({
    prop: 'source2'
  })
}),
value2: hash({
  prop1: 'source3'
}).defaults('value1'),
```

**Comment by kellyselden** [comment]
I'm not familiar with that API, so I'm not sure how easily it could be implemented.

**Comment by kellyselden** [comment]
`hash` returns a computed property, so I'm hesitant to add a `defaults` function to it.

Closing because I don't know how to progress this. I'm open to ideas. You could always make your own macro that merges hashes using [this](https://youtu.be/kIDIa1NBZZI?t=1118) as a guide. Then you could resubmit the API you come up with to see if it should be included here.
